# Replace these two values after creating your project on sonarcloud.io
# projectKey and organization are both shown on your SonarCloud project's
# "Information" page once you import the repo.
sonar.projectKey=testUser2354236_test-cicd
sonar.organization=testuser2354236

sonar.sources=.
